version: '3.1'

services:
  mysqldbmaster:
    build: ./mysqldbmaster
    container_name: test_db_master
    volumes:
    - ./mysqldbmaster/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test
  mysqldbslave:
    build: ./mysqldbslave
    container_name: test_db_slave
    volumes:
    - ./mysqldbslave/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: test
  phpmyadmin:
    container_name:  test_phpmyadmin_ms
    image: phpmyadmin:5.2.0-apache
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1